name: WorkFlow Patients Home

on:
  push:
    branches: [ master ]

env:
  KEY_PEM: ${{ secrets.KEY_PEM }}  
  
jobs:

  deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       
     - name: Pull repo
       uses: fifsky/ssh-action@master
       with:
         command: |
          cd patiensHomeAPI
          sudo pm2 stop PatientsAPI
          git pull origin master
          npm install
          sudo pm2 start PatientsAPI
         host: rpi-spilab.ddns.net
         user: ubuntu
         key: ${{ secrets.KEY_PEM }}